#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build per-day LLM input texts from extracted NewsML dataset."
    )
    parser.add_argument(
        "--current-csv",
        required=True,
        help="Path to news_current.csv generated by extract_news_dataset.py",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory to write daily LLM input files into.",
    )
    parser.add_argument(
        "--max-articles-per-day",
        type=int,
        default=200,
        help="Maximum number of articles to include in one daily LLM input.",
    )
    parser.add_argument(
        "--max-body-chars",
        type=int,
        default=600,
        help="Maximum number of body characters per article.",
    )
    return parser.parse_args()


def load_rows(path: Path) -> list[dict[str, Any]]:
    with path.open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def sort_key(row: dict[str, Any]) -> tuple[str, str, str]:
    return (
        row.get("source_timestamp_jst", ""),
        row.get("news_item_id", ""),
        row.get("raw_xml_path", ""),
    )


def clip_text(value: str, max_chars: int) -> str:
    value = (value or "").strip()
    if len(value) <= max_chars:
        return value
    return value[: max_chars - 1].rstrip() + "…"


def compact_json_list(raw: str) -> list[dict[str, Any]]:
    if not raw:
        return []
    return json.loads(raw)


def top_counter_lines(counter: Counter[str], limit: int = 10) -> list[str]:
    lines: list[str] = []
    for name, count in counter.most_common(limit):
        lines.append(f"- {name}: {count}")
    return lines


def article_block(row: dict[str, Any], max_body_chars: int) -> str:
    genres = compact_json_list(row.get("news_genres", ""))
    areas = compact_json_list(row.get("area_codes", ""))
    companies = compact_json_list(row.get("corporations", ""))

    genre_text = ", ".join(
        item["minor"] for item in genres if item.get("minor")
    )
    area_text = ", ".join(
        filter(None, [item.get("country", "") for item in areas])
    )
    company_text = ", ".join(
        item["name"] for item in companies if item.get("name")
    )

    lines = [
        f"### {row.get('headline', '').strip()}",
        f"- 配信時刻JST: {row.get('source_timestamp_jst', '')}",
        f"- NewsItemId: {row.get('news_item_id', '')}",
    ]
    if row.get("subheadline", "").strip():
        lines.append(f"- サブ見出し: {row['subheadline'].strip()}")
    if row.get("keyword_line", "").strip():
        lines.append(f"- キーワード: {row['keyword_line'].strip()}")
    if row.get("news_brand", "").strip():
        lines.append(f"- 商品種別: {row['news_brand'].strip()}")
    if genre_text:
        lines.append(f"- ジャンル: {genre_text}")
    if area_text:
        lines.append(f"- 関連国・地域: {area_text}")
    if company_text:
        lines.append(f"- 関連企業: {company_text}")
    body = clip_text(row.get("body_text", ""), max_body_chars)
    if body:
        lines.append("- 本文:")
        lines.append(body)
    return "\n".join(lines)


def build_daily_text(
    market_date: str,
    rows: list[dict[str, Any]],
    max_articles_per_day: int,
    max_body_chars: int,
) -> tuple[str, dict[str, Any]]:
    rows = sorted(rows, key=sort_key)
    selected = rows[:max_articles_per_day]

    genre_counter: Counter[str] = Counter()
    country_counter: Counter[str] = Counter()
    company_counter: Counter[str] = Counter()
    keyword_counter: Counter[str] = Counter()

    for row in selected:
        for item in compact_json_list(row.get("news_genres", "")):
            if item.get("minor"):
                genre_counter[item["minor"]] += 1
        for item in compact_json_list(row.get("area_codes", "")):
            if item.get("country"):
                country_counter[item["country"]] += 1
        for item in compact_json_list(row.get("corporations", "")):
            if item.get("name"):
                company_counter[item["name"]] += 1
        keyword_line = row.get("keyword_line", "").strip()
        if keyword_line:
            for keyword in [part.strip() for part in keyword_line.split("、") if part.strip()]:
                keyword_counter[keyword] += 1

    sections: list[str] = []
    sections.append(f"# Daily News Input")
    sections.append(f"- market_effective_date_jst: {market_date}")
    sections.append(f"- article_count_total: {len(rows)}")
    sections.append(f"- article_count_included: {len(selected)}")
    sections.append("")
    sections.append("## 集計サマリー")
    sections.append("このテキストは、日本語ニュース記事群を1日単位で要約するための入力です。")
    sections.append("記事間の重複や連続報道を考慮しつつ、その日の全体的な空気感、主要トピック、ニュース量の偏りを把握してください。")
    sections.append("")
    sections.append("### 上位ジャンル")
    sections.extend(top_counter_lines(genre_counter))
    sections.append("")
    sections.append("### 上位関連国・地域")
    sections.extend(top_counter_lines(country_counter))
    sections.append("")
    sections.append("### 上位関連企業")
    sections.extend(top_counter_lines(company_counter))
    sections.append("")
    sections.append("### 上位キーワード")
    sections.extend(top_counter_lines(keyword_counter))
    sections.append("")
    sections.append("## 記事一覧")

    for row in selected:
        sections.append("")
        sections.append(article_block(row, max_body_chars))

    text = "\n".join(sections).strip() + "\n"
    metadata = {
        "market_effective_date_jst": market_date,
        "article_count_total": len(rows),
        "article_count_included": len(selected),
        "max_articles_per_day": max_articles_per_day,
        "max_body_chars": max_body_chars,
        "top_news_genres": genre_counter.most_common(10),
        "top_countries": country_counter.most_common(10),
        "top_companies": company_counter.most_common(10),
        "top_keywords": keyword_counter.most_common(10),
    }
    return text, metadata


def main() -> None:
    args = parse_args()
    rows = load_rows(Path(args.current_csv))

    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        grouped[row["market_effective_date_jst"]].append(row)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest: list[dict[str, Any]] = []
    for market_date in sorted(grouped):
        text, metadata = build_daily_text(
            market_date,
            grouped[market_date],
            max_articles_per_day=args.max_articles_per_day,
            max_body_chars=args.max_body_chars,
        )
        txt_path = output_dir / f"{market_date}.txt"
        json_path = output_dir / f"{market_date}.json"
        txt_path.write_text(text, encoding="utf-8")
        json_path.write_text(
            json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        manifest.append(
            {
                "market_effective_date_jst": market_date,
                "txt_path": str(txt_path),
                "json_path": str(json_path),
                **metadata,
            }
        )

    (output_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )


if __name__ == "__main__":
    main()
